# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
# development:
#   adapter: postgresql
#   database: trellnote_db
#   host: localhost
#   pool: 5
#   timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: trellnote_development
  pool: 5
  timeout: 5000
  username: darshan
  password: s3nryuu13